wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1670681501.968895
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.8.15
      5: 0.13.6
      8:
      - 5
alpha:
  desc: null
  value: 10
backbone:
  desc: null
  value: googlenet
bs:
  desc: null
  value: 128
data_dir:
  desc: null
  value: ./dataset
dataset:
  desc: null
  value: cub
ee_l2norm:
  desc: null
  value: true
embedding_dim:
  desc: null
  value: 512
epochs:
  desc: null
  value: 5000
gpu_id:
  desc: null
  value: 0
img_size:
  desc: null
  value: 227
logpath:
  desc: null
  value: ./logs
loss:
  desc: null
  value: HPHNTriplet
lr:
  desc: null
  value: 0.0001
lr_decay_gamma:
  desc: null
  value: 0.5
lr_decay_step:
  desc: null
  value: 10,20,40,80
margin:
  desc: null
  value: 1.0e-05
model:
  desc: null
  value: googlenet
n_inner_pts:
  desc: null
  value: 2
num_instances:
  desc: null
  value: 32
num_workers:
  desc: null
  value: 10
optimizer:
  desc: null
  value: adam
recall_k:
  desc: null
  value: 1,2,4,8
soft_margin:
  desc: null
  value: false
weight_decay:
  desc: null
  value: 0.0005
